apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registryhtc1767.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        envFrom:
          - secretRef: 
              name: sql-credentials
---          
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  ports:
  - port: 80
    targetPort: 80
          
        
        