apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  labels:
    app: userprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      containers:
        - name: userprofile
          image: registryhtc1767.azurecr.io/tripinsights/userprofile:1.0
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: sql-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
spec:
  selector:
    app: userprofile
  ports:
    - port: 80
      targetPort: 80
