apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registryhtc1767.azurecr.io/tripinsights/tripviewer:1.0
          ports:
            - containerPort: 80
          env:
            - name: USERPROFILE_API_ENDPOINT
              value: 'http://userprofile-service.api'
            - name: TRIPS_API_ENDPOINT
              value: 'http://trips-service.api'
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-front
spec:
  ports:
    - port: 80
  selector:
    app: tripviewer
