apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripinsight-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: tripviewer-front
              servicePort: 80
