apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-pods
  namespace: web
subjects:
  - kind: Group
    name: 5cfcf782-f814-49ab-a4f7-2bdf0feb7399
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-pods
  namespace: web
subjects:
  - kind: Group
    name: 2244ab2a-a025-4e48-b3e3-3e6ab1af2bed
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
